### ISSUE TITLE
Macpatch client cannot run

### ISSUE THREAD

**Issue by kenny8708** [LLNL/MacPatch#127]
I installed the package (MacPatch Client ) directly from the master tree. It is installed, but when I run it, it terminated. 
Would you provide the guideline for client side? any config need ?

**Comment by cheizer** [comment]
Hello, this sounds like you did not upload it using the MPAgentUploader to the server first. Without this step the agent does not contain all of its configuration data to run properly.  Here are the docs on the agent build and upload.
https://macpatch-docs.llnl.gov/client_build_install.html

**Comment by Ardziv** [comment]
Thanks i tried the steps in the https://macpatch-docs.llnl.gov/client_build_install.html using the "master" branch as well as the "3.4.0-dev" branch - and the resulting PKG is throwing me the "**this package is incompatible with this version of macOS.**" (see below screenshots).

Do you have any idea what needs to be done to make it compatible to latest MACOSX Catalina 10.15?
**ERROR:**
<img width="732" alt="MacPatch-3 4 0-dev-CATALINA-error" src="https://user-images.githubusercontent.com/13898818/69848644-9536d280-12b5-11ea-8b61-1d4c32572648.png">

**MAC OS X Version:**
<img width="654" alt="MACOS-Catalina" src="https://user-images.githubusercontent.com/13898818/69848696-b992af00-12b5-11ea-9920-db7acabbafe3.png">

**Comment by Ardziv** [comment]
And same problem if I want to use the "Agent Uploader" pre-compiled on my MacPatch server - MacOS Catalina complains that the binary needs to be updated by developper 

ERROR:
<img width="532" alt="MPAgentUploader-ERROR-Catalina" src="https://user-images.githubusercontent.com/13898818/69851678-32e1d000-12bd-11ea-8d2d-3805e886e678.png">

**Comment by cheizer** [comment]
Sorry for the delay. I'm looking in to this right now.

**Comment by cheizer** [comment]
So, here is the oddness. I think the app needs to be notarized, which I'll work on doing but in the mean time you can right click on the .app and choose open. The app is still signed and will launch and run. Also, if you just copy the zip file from /opt/MacPatch/Source/Server/conf/Content/Web/tools/MPAgentUploader.zip to you desktop and unzip it; it will launch without the warning.
