### ISSUE TITLE
Can't seem to run server on Centos

### ISSUE THREAD

**Issue by omriman067** [LLNL/MacPatch#135]
Hey everyone.
iv'e been trying to install MacPatch on a centos and can't seem to be setup things smoothly.
i'm getting the following 2 tracebacks while running "./mpapi.py db upgrade head":
`/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1831, "Duplicate index 'ix_mp_client_reg                                                                                _keys_cuuid' defined on the table 'MacPatchDB3.mp_client_reg_keys'. This is deprecated and will be disallowed in a future release.")
  result = self._query(query)
/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'MacPatchDB3.mp_cli                                                                                ents_view'")
  result = self._query(query)
/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'MacPatchDB3.mp_cli                                                                                ent_patches_apple_view'")
  result = self._query(query)
/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'MacPatchDB3.mp_cli                                                                                ent_patches_third_view'")
  result = self._query(query)
/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'MacPatchDB3.mp_cli                                                                                ent_patches_full_view'")
  result = self._query(query)
/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'MacPatchDB3.combin                                                                                ed_patches_view'")
  result = self._query(query)
/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'MacPatchDB3.mp_cli                                                                                ent_patch_status_view'")
  result = self._query(query)
/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'MacPatchDB3.client                                                                                _patch_status_view'")
  result = self._query(query)
`

`   packet.check_error()
  File "/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/MacPatch/Server/env/api/lib64/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1072, "Key column 'tableName,modelTableName' doesn't exist in table")
[SQL: CREATE INDEX ix_mdm_intune_table_lastsync ON mdm_intune_table_lastsync ('tableName,modelTableName')]
(Background on this error at: http://sqlalche.me/e/2j85)
`

furthermore, when i start the app and browse to it in my browser i get "502 bad gateway".
has anyone encountered these problems?
thank you :)

**Comment by cheizer** [comment]
What version of CentOS?

**Comment by cheizer** [comment]
Found the issue. Index syntax was incorrect. The fix has been rolled in to the master branch. You will need to drop the MacPatch database and user and rerun the database setup. The database setup script has now been upgraded to a python script.
