### ISSUE TITLE
Repeating kernel panics on MacOS 10.14.6 supplemental update 2020-004

### ISSUE THREAD

**Issue by durack1** [LLNL/MacPatch#142]
Hi folks, I am hitting repeating ~2 x daily kernel panics on MacOS 10.14.6. This is really starting to disrupt my productivity as it started back on the 6th April 2020.

The kernel panic report indicates that the following processes were running when the crash occurs:

```
Anonymous UUID:       200CDD09-89F4-8020-9553-FF636BF784DA

Tue Jul 28 14:16:07 2020

*** Panic Report ***
panic(cpu 0 caller 0xffffff7f8df3fd44): "sfree on invalid allocation at 0xffffff8042ba14b0"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/Sandbox_executables/Sandbox-851.270.3/src/kext/smalloc.c:248
...
BSD process name corresponding to current thread: MPAgent

Mac OS version:
18G6020
```
In previous crashes, I have logged issues with the following threads:

BSD process name corresponding to current thread: WindowServer
find OR
launchd x2
kernel_task x3
fseventsd
trustd
sysinfocachegen
Finder
Microsoft Outloo x2
WindowServer x2
mdworker_shared x3
accountsd
xpcproxy

A colleague (@muryanto1) has also been suffering similar experiences with the following:

```
BSD process name corresponding to current thread: CrashPlanService
BSD process name corresponding to current thread: com.docker.backe
BSD process name corresponding to current thread: mdworker_shared
BSD process name corresponding to current thread: mdworker_shared
BSD process name corresponding to current thread: automountd
 
I also have lots of SymDaemon* crash files. They all say
Crashed Thread:        33  Dispatch queue: ClientSDK Service
or
Crashed Thread:        25  Dispatch queue: com.symantec.domainsetting.observer
```

I've engaged support and there is apparently a known issue with Symantec, which is patched up to the very latest 14.3.510.0000) Mac client version. As an FYI, apparently SEP releases are documented at https://knowledge.broadcom.com/external/article/154575. If this information is up-to-date, then we are running the latest (buggy) release

ping a number of colleagues who have also had problems @nathanlcarlson @abdulla1 @pochedls

**Comment by pochedls** [comment]
I had this issue on a personal computer and it was attributable to Symantec (it stopped if I used different antivirus software). This seemed to be a documented and unresolved problem of SEP.

**Comment by escobarj** [comment]
@durack1  I see you're an LLNL employee so I assume you're referring to an LLNL managed Mac? 
I won't go into too detail here, but I'll say that we've received similar kernel panic reports for other users and we believe the problem is related to a security product that we use. We are waiting on a resolution from the vendor, also some users have seen a significant improvement after upgrading to macOS 10.15. I recommend contacting your computer support to get more info on the upgrade. Or feel free to reach out to me at escobar6@llnl.gov if you prefer.

**Comment by durack1** [comment]
Thanks @escobarj, and yep an LLNLer (Dawn told me about that husband of hers).

I was a little reluctant to press the button on an update to 10.15.6 just in case I managed to get myself in a worse state than I started, but you're suggesting that this has been a solution for many others? Would you advocate for an update, or wait for the Symantec fix to land first?
